[개발] Records관련 저장 기능 부여 1차 수정
depromeet/sulsul-BE pull request #35
Opened 2022-05-19 12:43 UTC by RyooChan

## 📍 주요 변경사항

- Record -> Records 엔티티명 수정
- Records와 RecordsFlavor 동시 저장 기능 부여
- 전체 파일 조회 기능 적용

## 💡 중점적으로 봐주었으면 하는 부분

- Test는 다들 어떻게 진행하시나요?? pull받고 나니 구동에서 에러가 발생해서 Test가 안되네요...
- Beer이나 다른 Entity에서 기존의 Review에서 파일을 가져오는 소스가 있습니다. Review는 더이상 사용되지 않는 엔티티이기 때문에 수정 부탁드려요!
- 해당 소스는 Test를 진행하지 못한 것이기 때문에 실제로 에러가 발생할 수 있습니다. 
- 변수명 변경은 이후에 같이 통일을 논의해보고 한꺼번에 바꾸는것도 좋을 것 같습니다 :)

## 🔗 참고자료

2022-05-21 09:47 UTC, Ting-Kim requested changes
고생하셨습니다. 다만 Records로 바꾼 부분을 다시 Record로 롤백 후, 다시 테스트해보고 Merge를 진행해야 할 것 같습니다..! 수정 부탁드리겠습니다ㅠㅠ

2022-05-21 09:47 UTC, Ting-Kim commented on src/main/java/com/depromeet/sulsul/domain/record/controller/RecordController.java
> -public class RecordController {
음.. 찬님 `Record` -> `Records` 엔티티 자체를 바꾸자는 이야기가 아니라, `request resource`만 바꾸자는 제안이었습니다.
즉, 엔티티는 모두 `Record` 로 그대로 유지하는게 맞고, `request Uri` 만 `/api/v1/records `로 진행하는 의미였습니다..!

2022-05-21 09:47 UTC, Ting-Kim commented on src/main/java/com/depromeet/sulsul/domain/records/controller/RecordsController.java
> +@RequestMapping("/api/v1/records")
리소스는 잘 바꿔주셨습니다!
하지만 RecordsController, RecordsService 등 다시 RecordController, RecordService로 변경이 필요해보입니다.

2022-05-21 09:47 UTC, Ting-Kim commented on src/main/java/com/depromeet/sulsul/domain/records/dto/RecordsDto.java
> +    private MemberRecordsDto memberRecordsDto;
이러한 명칭도 Record로 부탁드립니다!

2022-05-21 09:47 UTC, Ting-Kim commented on src/main/java/com/depromeet/sulsul/domain/records/entity/Records.java
> +public class Records extends BaseEntity {
Record!

2022-05-21 09:47 UTC, Ting-Kim commented on src/main/java/com/depromeet/sulsul/domain/recordsFlavor/entity/RecordsFlavor.java
> +public class RecordsFlavor {
RecordFlavor로 부탁드립니다 :)

2022-05-24 08:10 UTC, RyooChan commented
아아 넵! 오늘 RECORDS로 변경하겠습니다!

2022-05-25 16:19 UTC, closed without merging