기록 조회 API 명세 및 내용 변경
depromeet/sulsul-BE pull request #39
Opened 2022-05-25 16:23 UTC by RyooChan

## 📍 주요 변경사항

- BaseEntity 내용 일부 변경
- API명세용 내용 변경
- POST와 RequestBody를 통한 조회
- Records이름 Record로 재변경

## 💡 중점적으로 봐주었으면 하는 부분
- 해당 내용은 batch_fetch_size를 사용했기 때문에 테스트 하실 때에 해당 테스트 내용을 yml에 적용하셔야 할 것 같습니다.
- gradle와 yml에의 변경사항은 따로 전달드리겠습니다!

## 🔗 참고자료

2022-05-25 17:23 UTC, Ting-Kim requested changes
고생하셨습니다! 필수적으로 수정이 필요한 부분은 개선 부탁드려요!
그리고 현재 민수님이 말씀해주신 `GoogleStyle` 코드 포맷팅이 적용 안된 것 같아요!
전체 코드에 적용 부탁드릴게요!

2022-05-25 17:23 UTC, Ting-Kim commented on src/main/java/com/depromeet/sulsul/domain/recordFlavor/service/RecordsFlavorService.java
> +        for(int i=0; i<recordsFlavorRequest.getFlavors().size(); i++){
여기서는 `for` 문을 돌면서 i 값을 체크하는 과정에서 `recordsFlavorRequest.getFlavors().size()` 가 반복해서 호출됩니다!
지역변수로 `size`를 구한 다음, 해당 변수를 사용하는 것을 추천드립니다 ☺️

2022-05-26 16:09 UTC, RyooChan commented on src/main/java/com/depromeet/sulsul/domain/record/controller/RecordController.java
> +    @PostMapping("/findRecords")
아 맞아요...이부분은 고민이 좀 되었습니다!
보통 save를 묵시적으로 POST를 사용하니까... 조회할 때에는 records/find 로 사용하는 식으로 진행하는건 어떨까요!?

2022-05-26 16:10 UTC, RyooChan commented on src/main/java/com/depromeet/sulsul/domain/record/service/RecordService.java
> +        }
넵 이거는 저도... 먼저 기능 구현이 일단락 된 이후에 다시 리팩터링 해보겠습니다!
코드 가독성도 너무 떨어지네요ㅜㅜ

2022-05-26 16:11 UTC, RyooChan commented
어 그런데 이상하네요... 구글 스타일 적용 했는데 왜 안되는지.... 다시 적용해 보겠습니다!

2022-05-26 16:15 UTC, closed without merging

2022-05-27 20:45 UTC, Ting-Kim commented
전체 패키지를 `드래그(선택)` 후 `ctrl+alt+L` 하시면 됩니다!

2022-05-27 20:47 UTC, Ting-Kim commented on src/main/java/com/depromeet/sulsul/domain/record/controller/RecordController.java
> +    @PostMapping("/findRecords")
음 듣고보니 그렇기도 하네요..!? `read, find` 같은 단어 중 하나 선택하면 될 것 같아요!